import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'what-is-physical-ai',
    'history-of-humanoid-robotics',
    'the-modern-humanoid-robot',
    'robot-anatomy-and-kinematics',
    'sensors-and-perception',
    'actuators-and-control',
    'introduction-to-ai-for-robotics',
    'machine-learning-for-perception',
    'reinforcement-learning-for-motion',
    'natural-language-processing-for-interaction',
    'simulating-humanoid-robots',
    'programming-humanoid-robots-with-ros',
    'hardware-and-software-integration',
    'human-robot-interaction',
    'ethics-and-social-impact',
    'the-future-of-humanoid-robotics',
  ],
};

export default sidebars;
